application: ghost-righters
version: 1
runtime: go
api_version: go1

handlers:
# - url: /form/.*
#   script: _go_app
#   secure: always
- url: /home/.*
  script: _go_app
  login: required

- url: /.*
  script: _go_app
